version: 0.2
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
  build:
    commands:
      - docker build -t my-app-test:latest .
  post_build:
    commands:
      - docker tag my-app-test:latest ${DOCKERHUB_USERNAME}/my-app-test:latest
      - docker push ${DOCKERHUB_USERNAME}/my-app-test:latest
