version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install python-pip -y
      - pip install -r requirements.txt
  build:
    commands:
      - python calc.py
artifacts:
  files: 
    - "**/*"
  base-directory: ../sources