name: MyFirstJob

on: 
  push:
      branches: [main]
  workflow_dispatch:


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: greet user
        run: echo "Welcome to the New World"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: greet user
        run: echo "Welcome to the New World"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: greet user
        run: echo "Welcome to the New World"
